### ISSUE TITLE
where is the code?

### ISSUE THREAD

**Issue by peczenyj** [InteractiveAdvertisingBureau/Consent-String-SDK-C#1]
Hello

I can't find the source code, something happens?

**Comment by mnicky** [comment]
Maybe they are waiting for community contribution similarly to what (probably) happened for Scala SDK.

**Comment by mnicky** [comment]
@jenniferIAB are there any plans on getting this released?

**Comment by chrispaterson** [comment]
Hi, @peczenyj and @mnicky this codebase was never created.  However, a new effort is underway for v2.0 of the TCF to create a utility.

**Comment by mnicky** [comment]
Thanks for the information @chrispaterson! So is there any approximate date when we can expect the release?
